# Generated by Django 3.2 on 2022-01-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
